project:
  type: website

website:
  title: "Practical Cryptography In Python"
  navbar:
    left:
      - href: index.qmd
        text: Home
  sidebar: 
    style: "docked"
    search: false 
    contents: auto

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



