project:
  type: website

website:
  title: "Practical Cryptography In Python"
  navbar:
    left:
      - href: index.qmd
        text: Home
    tools:
      - icon: github
        href: https://github.com/noahabe/practical_cryptography_in_python_answers.git
  sidebar: 
    style: "docked"
    collapse-level: 1
    search: false 
    contents: auto

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



